// <auto-generated />
namespace OnlineBank.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Transaction_currentbalance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Transaction_currentbalance));
        
        string IMigrationMetadata.Id
        {
            get { return "201808131823127_Transaction_currentbalance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
